language: node_js

node_js:
 - "8"

dist: trusty
# https://docs.travis-ci.com/user/database-setup/#mysql-57
sudo: true

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client

services:
  - mysql

notifications:
  email:
    - dcoates@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
  - npm config set spin false

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS fxa'
  - npm i grunt-cli -g
  - npm run outdated
  # HACK: ignore npm audit errors for now until we get them all fixed
  - npm audit || true

script:
  - npm run test-travis
  - npm run explain
